import { TypographyOptions } from '@mui/material/styles/createTypography'

const typography: TypographyOptions = {
  htmlFontSize: 16,
  fontFamily: '"Ubuntu", sans-serif',
  fontSize: 14,
  fontWeightLight: 300,
  fontWeightRegular: 400,
  fontWeightMedium: 500,
  fontWeightBold: 700,
  h1: {
    fontFamily: '"Ubuntu", sans-serif',
    lineHeight: 1.167,
    fontWeight: 700,
    fontSize: 40,
    letterSpacing: '-0.24px',
  },
  h2: {
    fontFamily: '"Ubuntu", sans-serif',
    lineHeight: 1.2,
    fontWeight: 700,
    fontSize: 29,
    letterSpacing: '-0.24px',
  },
  h3: {
    fontFamily: '"Ubuntu", sans-serif',
    lineHeight: 1.167,
    fontWeight: 700,
    fontSize: 24,
    letterSpacing: '-0.06px',
  },
  h4: {
    fontFamily: '"Ubuntu", sans-serif',
    lineHeight: 1.235,
    fontWeight: 500,
    fontSize: 20,
    letterSpacing: '-0.06px',
  },
  h5: {
    fontFamily: '"Ubuntu", sans-serif',
    lineHeight: 1.334,
    fontWeight: 700,
    fontSize: 16,
    letterSpacing: '-0.05px',
  },
  h6: {
    fontFamily: '"Ubuntu", sans-serif',
    lineHeight: 1.6,
    fontWeight: 700,
    fontSize: 14,
    letterSpacing: '-0.05px',
  },
  subtitle1: {
    fontFamily: '"Ubuntu", sans-serif',
    fontWeight: 400,
    fontSize: '1rem',
    lineHeight: 1.75,
    letterSpacing: '0.00938em',
  },
  subtitle2: {
    fontFamily: '"Ubuntu", sans-serif',
    fontWeight: 500,
    fontSize: '0.875rem',
    lineHeight: 1.57,
    letterSpacing: '0.00714em',
  },
  body1: {
    fontFamily: '"Ubuntu", sans-serif',
    fontWeight: 400,
    fontSize: '1rem',
    lineHeight: 1.5,
    letterSpacing: '0.00938em',
  },
  body2: {
    fontFamily: '"Ubuntu", sans-serif',
    fontWeight: 400,
    fontSize: '0.875rem',
    lineHeight: 1.43,
    letterSpacing: '0.01071em',
  },
  button: {
    fontFamily: '"Ubuntu", sans-serif',
    fontWeight: 400,
    fontSize: '0.875rem',
    lineHeight: 1.75,
    letterSpacing: '0.02857em',
    textTransform: 'unset',
  },
  caption: {
    fontFamily: '"Ubuntu", sans-serif',
    fontWeight: 400,
    fontSize: '0.75rem',
    lineHeight: 1.66,
    letterSpacing: '0.03333em',
  },
  overline: {
    fontFamily: '"Ubuntu", sans-serif',
    fontWeight: 500,
    fontSize: '0.75rem',
    lineHeight: 2.66,
    letterSpacing: '0.08333em',
    textTransform: 'uppercase',
  },
}

export default typography
